### ISSUE TITLE
mesh not importing but the rig is imported

### ISSUE THREAD

**Issue by Mrkkama** [Befzz/blender3d_import_psk_psa#96]
i just gives me this error 

Python: Traceback (most recent call last):
  File "/io_import_scene_unreal_psa_psk_280.py", line 2224, in execute
    if not pskimport_proxy():
  File "/io_import_scene_unreal_psa_psk_280.py", line 2205, in pskimport_proxy
    return pskimport( 
  File "/io_import_scene_unreal_psa_psk_280.py", line 1172, in pskimport
    bone_group_unused = armature_obj.pose.bone_groups.new(name = "Unused bones")
AttributeError: 'Pose' object has no attribute 'bone_groups'

**Comment by mubeen1729** [comment]
Just use Blender 2.83 to import the files, and export it as FBX to be used in other versions of Blender. 
I got the same error in blender 3.x versions and blender 4 too - worked fine in 2.83 LTS.

**Comment by 4rtb** [comment]
Same error (tried on blender 4.0, blender 3.6 works)
